# Pre-commit configuration.
# https://pre-commit.com

# pre-commit install --install-hooks -t pre-commit -t commit-msg
# pre-commit run --all-files

default_stages:
  - pre-commit
  - pre-push
  - commit-msg
  - manual

repos:
  # Fix some errors with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        args: [ --fix, --exit-zero ]
        name: "ruff: fixing"
      - id: ruff-format
        name: "ruff: formatting"

  # Lint Python files with Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.0
    hooks:
      - id: ruff
        name: "ruff: linting"

  # Check other files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: alembic/
      - id: end-of-file-fixer
        exclude: alembic/
      - id: check-added-large-files

  # Generate requirements.txt
  - repo: local
    hooks:
      - id: generate-requirements-txt
        name: generate requirements.txt
        language: system
        entry: poetry export -f requirements.txt --output requirements.txt
        pass_filenames: false
        files: ^(pyproject.toml|poetry.lock)$
