model_name: logistic_regression
artifact_path: basic_lr

tag_key: "model"
tag_value: "basic LR"

module_name: "sklearn.linear_model"
class_name: "LogisticRegression"

hydra:
  sweeper:
    params:
      penalty: ['l1', 'l2']
      solver: ['saga']
      max_iter: [100, 200, 1000]
      random_state: [88]
      C: [0.1, 0.5, 0.8]
