defaults:
  - _self_

folds: 5
best_model_name: ""
best_model_alias: ""
labels: ""

evaluation_metric: "f1"
cv_evaluation_metric: "mean_test_f1"

pyfunc_predict_fn: "predict_proba"

metrics:
  accuracy: "accuracy"
  f1: "f1"
