defaults:
  - _self_

folds: 3

evaluation_metric: "f1_weighted"
cv_evaluation_metric: "mean_test_f1_weighted"

pyfunc_predict_fn: "predict_proba"

metrics:
  accuracy: "accuracy"
  f1: "f1_weighted"

best_model_name: "xgboost"
best_model_alias: "champion"
labels: {false: "on-time", true: "cancelled"}
