model_name: random_forest
artifact_path: basic_rf

tag_key: "model"
tag_value: "basic RF"

module_name: "sklearn.ensemble"
class_name: "RandomForestClassifier"

hydra:
  sweeper:
    params:
      n_estimators: [100, 200, 500]
      criterion: ['gini', 'entropy', 'log_loss']
      min_samples_leaf: [2, 4, 6]
