model_name: random_forest
artifact_path: basic_rf

tag_key: "model"
tag_value: "basic RF"

module_name: "sklearn.ensemble"
class_name: "RandomForestClassifier"

hydra:
  sweeper:
    params:
      n_estimators: [100, 200, 500]
      criterion: ['gini', 'entropy', 'log_loss']
      max_depth: [1500,2000,2500]
      bootstrap: [True, False]
