model_name: xgboost
artifact_path: basic_xgboost

tag_key: "model"
tag_value: "basic xgboost"

module_name: "xgboost"
class_name: "XGBClassifier"

hydra:
  sweeper:
    params:
      learning_rate: [0.05, 0.1, 0.2]
      gamma: [0.1, 0.3, 0.4]
      colsample_bytree: [0.5, 0.9, 1.0]
