model_name: xgboost
artifact_path: basic_xgboost

tag_key: "model"
tag_value: "basic xgboost"

module_name: "xgboost"
class_name: "XGBClassifier"

hydra:
  sweeper:
    params:
      booster: ["gbtree"]
      learning_rate: [0.1]
      max_depth: [1500]
  


# booster: ["gbtree","dart"]
#       learning_rate: [0.05, 0.1, 0.2]
#       max_depth: [1500,2000]
#       tree_method: ["exact","approx","hist"]