required:
  - "Airline"
  - "ArrTimeBlk"
  - "CRSArrTime"
  - "CRSDepTime"
  - "CRSElapsedTime"
  - "Cancelled"
  - "DOT_ID_Marketing_Airline"
  - "DOT_ID_Operating_Airline"
  - "DayOfWeek"
  - "DayofMonth"
  - "DepTimeBlk"
  - "Dest"
  - "DestAirportID"
  - "DestAirportSeqID"
  - "DestCityMarketID"
  - "DestStateFips"
  - "DestWac"
  - "Distance"
  - "DistanceGroup"
  - "DivAirportLandings"
  - "Flight_Number_Marketing_Airline"
  - "Flight_Number_Operating_Airline"
  - "Month"
  - "Origin"
  - "OriginAirportID"
  - "OriginAirportSeqID"
  - "OriginCityMarketID"
  - "OriginStateFips"
  - "OriginWac"
  - "Quarter"
hash_features:
  - "ArrTimeBlk"
  - "DepTimeBlk"
  - "Airline"
  - "Origin"
  - "Dest"
hhmm:
  - "CRSArrTime"
  - "CRSDepTime"
  - "CRSElapsedTime"
time_features:
  - - "Month"
    - 12
  - - "DayofMonth"
    - 31
  - - "Quarter"
    - 4
