required:
  - "ActualElapsedTime"
  - "AirTime"
  - "Airline"
  - "ArrDelayMinutes"
  - "ArrTime"
  - "CRSArrTime"
  - "CRSDepTime"
  - "CRSElapsedTime"
  - "Cancelled"
  - "DayOfWeek"
  - "DayofMonth"
  - "DepDelayMinutes"
  - "DepTime"
  - "Dest"
  - "DestStateFips"
  - "DestWac"
  - "Distance"
  - "IATA_Code_Marketing_Airline"
  - "IATA_Code_Operating_Airline"
  - "Marketing_Airline_Network"
  - "Month"
  - "Operated_or_Branded_Code_Share_Partners"
  - "Operating_Airline"
  - "Origin"
  - "OriginStateFips"
  - "OriginWac"
  - "Quarter"
  - "TaxiIn"
  - "TaxiOut"
  - "WheelsOff"
  - "WheelsOn"
hhmm:
  - "CRSArrTime"
  - "CRSDepTime"
  - "CRSElapsedTime"
time_features:
  - - "Month"
    - 12
  - - "DayOfWeek"
    - 7
  - - "DayofMonth"
    - 31
  - - "Quarter"
    - 4
