data:
  url: https://drive.google.com/uc?id=1CKXjF6xZEgjYsdwfCMxoHChI7J5WjjdI
  output: datastore/data.csv
  datastore_path: datastore/data.csv
  sample_path: data/samples/sample.csv
  sample_version_path: data/samples/sample.csv.dvc
  sample_size: 0.2
  last_included_row_number: 815663
  data_version: v1.0
  version_number: 1
