data:
  url: https://drive.google.com/uc?id=1CKXjF6xZEgjYsdwfCMxoHChI7J5WjjdI
  output: project/datastore/data.csv
  datastore_path: project/datastore/data.csv
  sample_path: project/data/samples/sample.csv
  sample_version_path: project/data/samples/sample.csv.dvc
  context_dir_path: project/services
  sample_size: 0.2
  last_included_row_number: 0
  data_version: ""
  version_number: 0
